intro_a_1: "Open Draft is a research colloquium focusing on open-ended questions. We invite researchers and practitioners across the HfG & ZKM to present their ongoing research projects."
intro_a_2: "What are you curious about right now? What are some the ideas that you are toying with? What presentation formats are you trying out? What dead-ends are you looking for a way out of?"
intro_b_1: "We convene monthly at the HfG to offer a space to exchange, workshop and bounce ideas across disciplines and career stages."
intro_b_2: "All sessions take place at the <em>Lichtbrücke</em> and start at 18:00."
contact_text: "To participate and share ongoing work, write one of the organisers:"
email_1: "lxynogala@hfg-karlsruhe.de"
email_2: "hulas@hfg-karlsruhe.de"
year: "2025/2026"
